import Head from "next/head";
import { EntryContainer, EntryBtn } from "../styles/styles";
import Link from "next/link";

export default function Entry() {
  return (
    <EntryContainer>
      <Head>
        <title>Portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/home">
        <EntryBtn>
          <a>Gabriel Jaccoud</a>
        </EntryBtn>
      </Link>
    </EntryContainer>
  );
}
